services:
  - type: web
    name: everyunse
    env: node
    plan: free
    buildCommand: npm ci && npm run db:push && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: everyunse-db
          property: connectionString
      - key: OPENAI_API_KEY
        sync: false
      - key: KASI_API_KEY
        sync: false
      - key: KASI_LUNAR_API_KEY
        sync: false
      - key: VITE_PORTONE_STORE_ID
        sync: false
      - key: VITE_PORTONE_CHANNEL_KEY
        sync: false
      - key: PORTONE_API_KEY
        sync: false
      - key: PORTONE_API_SECRET
        sync: false
      - key: SESSION_SECRET
        generateValue: true
      - key: PORT
        value: 10000

databases:
  - name: everyunse-db
    plan: free