name: Deploy to Render

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
        cache: 'npm'
    
    - name: Install dependencies
      run: npm ci
    
    - name: Build application
      run: npm run build
      env:
        NODE_ENV: production
    
    - name: Deploy to Render
      if: github.ref == 'refs/heads/main'
      run: |
        echo "Deployment triggered for Render"
        # Render will automatically deploy when main branch is updated
        curl -X POST "https://api.render.com/deploy/srv-$RENDER_SERVICE_ID" \
             -H "Authorization: Bearer $RENDER_API_KEY"
      env:
        RENDER_SERVICE_ID: ${{ secrets.RENDER_SERVICE_ID }}
        RENDER_API_KEY: ${{ secrets.RENDER_API_KEY }}